// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joxogaoweoxverfobrym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpveG9nYW93ZW94dmVyZm9icnltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NDk5OTEsImV4cCI6MjA2MzMyNTk5MX0.FlhzZByveVmmWgZ61qtEUBRPY_HzpxlfV_eGKuUrrt0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);